from cohere.classify import Example
import cohere
import dotenv
import os

dotenv.load_dotenv()

co = cohere.Client(os.getenv("COHERE_API_KEY"))

# 1. Tell me about yourself
examples = [
    # bad
    Example("Well, I’ve always been interested in tech. But it all probably started when I was a kid, and at the age of 9 I first got my computer. I always loved playing around with code and learning new things. But it wasn’t until that high school where I first had my first class about it that really made me fall in love with the subject. Since then, I started learning more about it and decided to major in IT at University X where I learned how to.", "Bad"),  # 1
    Example("I’m an experienced, passionate business leader and inventor. I drive my team to be innovative and get results. I’ve mastered the craft of business development. I’ve really seen it all and have done every kind of deal imaginable.", "Bad"),  # 2
    Example("I’ve always been really interested in computers. I guess for the past nine years now I’ve been a programmer, but my passion for tech started way back when I was a kid. I’ve always loved monkeying around with code, but it wasn’t until I moved to Arizona that I tried to make a living off it. I got really into it and I can’t imagine doing anything else.", "Bad"),  # 3
    Example("Well, I’ve been a receptionist for the past seven years and I love it. You know, interacting with all the people and taking calls and just working with people in general. I’m a people person. I love the back and forth and energy. Even on my days off I love hanging out with friends and being around family. I’m also a hard worker and I’m very dependable.", "Bad"),  # 4
    Example("I am 44, from NY, work in Human Resources. No kids, 2 dogs. Shy until I am comfortable. I love dogs and cats, bilingual and love prime time cops shows such as FBI, Blue bloods, amd criminal minds.", "Bad"),  # 5
    # Example("lorem", "Bad"),  # 6
    # Example("lorem", "Bad"),  # 7
    # Example("lorem", "Bad"),  # 8
    # Example("lorem", "Bad"),  # 9
    # Example("lorem", "Bad"),  # 10
    # Example("lorem", "Bad"),  # 11
    # Example("lorem", "Bad"),  # 12
    # Example("lorem", "Bad"),  # 13
    # Example("lorem", "Bad"),  # 14
    # Example("lorem", "Bad"),  # 15
    # Example("lorem", "Bad"),  # 16
    # Example("lorem", "Bad"),  # 17
    # Example("lorem", "Bad"),  # 18
    # Example("lorem", "Bad"),  # 19
    # Example("lorem", "Bad"),  # 20

    # good
    Example("Sure, so, my name is Joe and I am 27 years old. For the past 5 years, I’ve been working as a business analyst at Company X and Y.I have some background in data analysis, with a degree from University XY. What really got me into the field, though, is the internship I did at Company Z. Throughout my career, I’ve noticed that I’ve always been good with numbers and handling data. For example, when I was working at Company X, I led a project for migrating all operations data to a new data warehousing system to cut down on costs. The new solution was a much better fit for our business, which eventually led to savings of up to $200,000 annually. Moving forward, I hope to expand my experience across different industries. Particularly fintech, which is why I’m interested in your company.", "Good"),  # 1
    Example("Sure, I’d be glad to. I’m an tech-focused project manager for up to 8 years now. I graduated from University X, where I made the Dean’s List, with a major in business administration and a minor in computer science. After that, I first got into the industry working as an administrative assistant at Company X. There I provided clerical support with interdepartmental communication, helped in managing schedules, and maintained the digital filing system. After that, I was working as a project manager for Company Y that provided cloud computing solutions for about 6 years. There, I personally managed 5+ teams of software projects, and made sure everything went smoothly in terms of business goals, deadlines, budget, and more. In my downtime, I enjoy reading about AI, tech, and robotics. Since you guys do all 3, I thought I’d apply. ", "Good"),  # 2
    Example("My name is Jane Doe, I’m 22 years old and I recently graduated from University X with a B.A. in international business. While there, I learned a lot of theory in subjects like corporate communication, international economics, corporate governance, and more. I was also part of the student government, and maintained a GPA of 3.6. I’ve worked hard in my education and now I’m ready to apply my knowledge into practice. While I don’t have any real-life work experience, I’ve had a lot of exposure to the business environment. A lot of my courses involved working with real companies to solve real problems. Now, I’m looking to leverage everything I’ve learned in uni and get some hands-on work experience. So, my name is John, and I’m a senior at School XYZ.  This year, I managed to maintain a 3.7 GPA, while working on a few different school projects. I started an ‘Ernest Hemingway Book Club’ which has up to 15 active members as of now. And I also launched a recycling program for the campus, through which we raised awareness and invited an outside guest lecturer to speak about the subject. I tend to be teamwork-oriented and reliable, as I’ve never missed a deadline. I’m also proud of my ability to preserve and overcome any challenges as they come up. For example, last year, I was having some trouble with trigonometry. I realized I needed to dedicate more time to the subject, so, I met with a teacher outside the class and set aside two extra hours per day for the subject. Eventually, I ended up with an A in the subject. At University X, I’m planning to either major in English or Journalism. I love reading and writing, so I think both programs are going to be interesting and relevant to my interests.", "Good"),  # 3
    Example("Hey! So, my name is John Doe and I’ve worked as a business analyst for 5+ years in Company X and Company Y. I have some background in data analysis, having studied Information Systems at [Made-Up] University. Throughout my career, I’ve done some pretty impressive stuff (if I do say so myself, haha). For example, at Company X, I led a project for migrating all operations data to a new data warehousing system to cut down on costs. The new solution was a much better fit for our business, which eventually led to savings of up to $200,000 annually. I am Jane Doe, a recent college graduate from the University of Wisconsin-Madison. I have just graduated with honors in Biochemistry. I know my way around a lab and have had multiple opportunities to put my knowledge into practice as a chemistry research assistant. The lab felt like home, which is why I’d love to work as a lab assistant. I am passionate, hard-working, and extremely responsible. I am also looking forward to putting to practice all the things I learned during my time at university.", "Good"),  # 4
    Example("Sure! So I've always enjoyed writing and public speaking, even as far back as high school. This led me to pursue writing-related passions—for example in college, where I was an editor for our school newspaper. In addition to writing, I got to learn how to manage a team and how to approach the writing process. After college, I took a job at Acme as a social media manager, writing copy and social content for the company blog, but I raised my hand to work on the communications plan for a product launch, which is where I discovered my interest in product marketing. After switching to a product marketing role and managing the two most successful new product launches last year, I realized I'm excited to take on a new opportunity. I've learned I work best on products that I love and use, and given that I'm a big user of your company’s products, I jumped at the chance to apply when I saw the open posting", "Good"),  # 5
    Example("Well, I’m currently an account executive at Smith, where I handle our top performing client. Before that, I worked at an agency where I was on three different major national healthcare brands. And while I really enjoyed the work that I did, I’d love the chance to dig in much deeper with one specific healthcare company, which is why I’m so excited about this opportunity with Metro Health Center.", "Good"),  # 6
    Example("I've been in the marketing industry for over five years, primarily working in account and project management roles. I most recently worked as a senior PM for a large tech company managing large marketing campaigns and overseeing other project managers. And now I'm looking to expand my experience across different industries, particularly fintech, which is why I'm so interested in joining an agency like yours.", "Good"),  # 7
    Example("Absolutely! I graduated from Howard in May with a major in computer science and a minor in theater arts and have been spending this summer interning at a theater nonprofit. I’ve had a chance to put my coding skills to good use by helping revamp the organization’s ticket sales page. Since it launched two weeks ago, the time it takes patrons to get through the purchasing process has decreased by 43% and scores on a popup satisfaction survey have gone up by nearly 20%. It’s been particularly exciting to be immersed in this environment because I’ve been in love with theater since I did my first school play in 7th grade—it was 13: The Musical and I landed the role of Patrice—and even led The Howard Players my senior year. This internship experience has only reinforced my desire to merge my CS skills with my passion for theater, which is why I knew I had to apply as soon as I saw the junior web developer role here.", "Good"),  # 8
    Example("I’ve spent the first decade of my career working in account management for SaaS startups selling B2B software, including my current company, which develops remote collaboration tools. And for the last couple of years I’ve been managing three to five direct reports. I’ve found people management incredibly fulfilling, and have been especially drawn to training and professional development. One of the accomplishments I’m proudest of in my job now was creating a series of upskilling workshops not just for my own team but for the entire revenue org. Account managers and sales reps who participated showed an average increase of 22% in sales or renewal revenue per quarter. Looking back, it makes so much sense that I’ve gravitated in this direction, considering I tutored and led workshops for the comms department in college. As I’ve thought about my next steps, I realized I wanted to transition into an HR role so that I can focus all of my energy on creating and implementing training programs. I can’t think of a better place to start than at a company that makes software I’ve relied on in multiple previous jobs.", "Good"),  # 9
    Example("I’ve been working as an administrative assistant for three years. At my current job in the finance department of a midsize company, I handle scheduling, meeting and travel planning for four executives and 20 staff members. I also help prepare correspondence, presentations and reports.", "Good"),  # 10
    Example("I’m known for being a detail-oriented, well-organized team player. I never miss deadlines, I’m a good communicator and I can juggle multiple tasks at once. In my performance reviews, my supervisor always notes that he appreciates my professionalism and enthusiasm for the job.", "Good"),  # 11
    Example("With this experience under my belt, I’m looking for an opportunity to take the next step in my career. I’m hoping to do so in an organization like yours that works to improve the environment, which is something I’m passionate about.", "Good"),  # 12
    Example("Before [Company Y] at [Company X], I was in customer service. I used to answer 100 tickets a day resolving customer issues. This experience helped me develop empathy for users. I learned how to put myself in the user’s shoes, which has helped me write better product value propositions that resonate with users.", "Good"),  # 13
    Example("When I’m not working, I like to spend time exploring with my dogs. I take them hiking, visiting historical sites, or even just walking around town. A surprising number of people are drawn to dogs, and I always enjoy talking with who I meet. I feel that communication is one of the most important aspects of my professional life as well. When talking with people, being able to guide the conversation in a particular direction is one of the ways I’ve been successful in different situations at the office.", "Good"),  # 14
    Example("I participate in charity walks several times a year. Recently, I did the Walk for Hunger and I have a few events planned for the summer and fall, as well. I walk for exercise with friends after work and on the weekends. I enjoy the fresh air, learning new routes, and connecting with new people. I also like the fundraising aspect, which has come in handy in my job. I’ve learned how to connect with people to increase their commitment to the cause.", "Good"),  # 15
    Example("The past few years, I’ve gotten really into geocaching. I love the challenge of finding caches and spending time outdoors with friends. I like using my problem-solving skills to find the ones that are really well-hidden. Learning how people hide things—and where people are likely to look—has helped me tremendously in my design work. It’s all about learning to see things through someone else’s eyes.", "Good"),  # 16
    Example("(1) I really enjoy providing robust software solutions. (2) I’ve led a software engineering team of 10 programmers at Xyzzy Solutions for three years. (3) Our proudest moment was receiving the 2018 Bossie award. (2) Before that I worked for two years as a software engineer at SurgeWallop. (3) I slashed security breaches 70% by winning full employee buy-in for our Principle of Least Privilege drive. (4) It’s been a great run, but I’m chafing at the bit to sink my teeth in with a high-performing DevOps team like the one at Brass LAMP Dev.", "Good"),  # 17
    Example("Well, I thrive in the excitement of a fast-paced office. As a receptionist at Drake & Caswell, I loved interacting with our 200 regular clients and managing training and travel schedules for 25 employees. Before that at Mindon Well Drilling, I really enjoyed being the contact point for hundreds of client calls and visits every week. In fact, I saved 20 management hours a month by triaging calls and emails. Those were great opportunities, but I’m at the point where this position at Maven Consulting Solutions would really let my talents shine.", "Good"),  # 18
    Example("I thrive in a fast-paced office where I can work on ratcheting up efficiency. At Castle Rock Mineral we often had over 100 customers a day come through the doors. I was able to cut scheduling errors by 25% and resolve complaints 50% faster than the previous assistant. Before that at TD Dental, I helped raise patient satisfaction scores 20% by streamlining our intake flow. I’m ready to grow into a position where my efficiency can make a difference to a larger team. That’s why I’m so excited about this role.", "Good"),  # 19
    Example("I’m a prolific web developer. At ExamTeam5, I regularly completed full-stack development for websites in 7 or 8 weeks. I cut delivery times at VerifEye Solutions by 30%. I enjoyed both positions, but HF7 Technologies is well-known for its aggressive work schedule. I think my productivity would really be valued here.", "Good"),  # 20
    Example("I love using my talents to bring more business to a worthy product. I worked as marketing manager at Ninequist Interactive for three years. During that time, my team and I presided over a period of 40% revenue growth. Before that at Spintegrity, I was able to increase conversions for email campaigns by 25%. I’m ready for a bigger challenge, and I would thrive in a fast-growing tech firm like Sequoia5 Global.", "Good"),  # 21
    Example("I really enjoy working as an OR nurse. For three years at Chrontos Medical, I received consistent commendations for my performance in the peri-operative setting. Before that at Barstow General, I was first-choice for the team of 15 surgeons. I’ve enjoyed every step along the way. Mass General was my first choice when I moved East because of your reputation for high-level health care in a safe, compassionate environment.", "Good"),  # 22
    Example("When I’ve got a product I believe in, I excel at selling it. I’ve loved working as a sales associate at Peterboro-Munchen for the past two years. The job gave me an opportunity to increase revenue by over $100,000 a year for some of the best pumps and hoses on the market. Before that at Belsden Group, I consistently outsold the other ten reps by 10% to 15%. Again, great product. Those were both great positions and I learned a lot, but now I really want to show what I can do. You’ve got the most respected, highest value security systems in the world, and a big market to sell them in. I’m very excited at the chance to use my skills to put your revenue through the roof.", "Good"),  # 23

]

# manual entry for testing
inputs = [
    "lorem sucks",  # bad
    "lorem dumbass",  # bad
    "lorem love",  # good
    "lorem good"  # good
]

response = co.classify(
    model='medium',  # Consider changing to large?
    inputs=inputs,
    examples=examples)

print(response.classifications)
